name: geojson
description: Utilities to work with geojson data. Parser with a reactive api,
  search and geofencing
homepage: https://github.com/synw/geojson
version: 1.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  geodesy: ^0.4.0-nullsafety.0
  geopoint3: ^0.9.1
  #iso: ^1.0.0
  iso:
    git:
      url: https://github.com/sirkalmi/iso.git
      ref: 1.0.1
  pedantic: ^1.11.1

dev_dependencies:
  #extra_pedantic: ^1.4.0
  test: ^1.17.4
